#!/bin/bash


MODULES="
@ionic-native/device-feedback
@ionic-native/dialogs
@ionic-native/local-notifications
@ionic-native/native-audio
@ionic-native/camera
"
for MODULE in $MODULES
do
	npm --save install $MODULE
done


npm install --save  d3
                        d3-scale
                        d3-array
                        d3-shape
                        d3-interpolate
                        d3-color
                        d3-time-format
                        d3-ease
                        d3-transition
                        d3-selection
                        d3-time
                        d3-path
                        d3-dispatch
                        d3-format
                        d3-timer
                        d3-drag
                        d3-geo
                        d3-brush
                        d3-dsv
                        d3-random

    npm i -g cordova
    ionic cordova plugin add cordova-plugin-insomnia
    npm install @ionic-native/insomnia
	
ionic cordova plugin add cordova-plugin-camera
